//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainCheckV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public decimal model_id { get; set; }
        public decimal make_id { get; set; }
        public string make_name { get; set; }
    
        public virtual make make { get; set; }
    }
}
