//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainCheckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coverage_level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coverage_level()
        {
            this.policy_tbl = new HashSet<policy_tbl>();
            this.policy_tbl1 = new HashSet<policy_tbl>();
            this.policy_tbl2 = new HashSet<policy_tbl>();
            this.policy_tbl3 = new HashSet<policy_tbl>();
        }
    
        public decimal level_id { get; set; }
        public decimal limite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_tbl> policy_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_tbl> policy_tbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_tbl> policy_tbl2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_tbl> policy_tbl3 { get; set; }
    }
}
