//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainCheckV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_tbl()
        {
            this.logins = new HashSet<login>();
        }
    
        public decimal customer_id { get; set; }
        public decimal userid { get; set; }
        [Required]
        [RegularExpression("^[0-9]{10,10}$", ErrorMessage = "Invalid ID Number, Only 10 digits")]
        public decimal driver_license_number { get; set; }
        public System.DateTime join_date { get; set; }
    
        public virtual user_tbl user_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> logins { get; set; }
    }
}
