//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainCheckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public decimal login_id { get; set; }
        public decimal customer_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
    
        public virtual customer_tbl customer_tbl { get; set; }
    }
}
