//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using RainCheckV2.common;

namespace RainCheckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_tbl
    {
        public decimal policy_id { get; set; }
        public decimal policy_number { get; set; }
        public decimal car_id { get; set; }
        public decimal user_id { get; set; }
        [Required]
        [ValidateDateRangeAttribute]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime start_date { get; set; }
        [Required]
        [ValidateDateRangeAttribute]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime end_date { get; set; }
        public decimal policy_amount { get; set; }
        public decimal self_property { get; set; }
        public decimal self_body { get; set; }
        public decimal opposite_property { get; set; }
        public decimal opposite_body { get; set; }
    
        public virtual car car { get; set; }
        public virtual coverage_level coverage_level { get; set; }
        public virtual coverage_level coverage_level1 { get; set; }
        public virtual coverage_level coverage_level2 { get; set; }
        public virtual coverage_level coverage_level3 { get; set; }
        public virtual user_tbl user_tbl { get; set; }
    }
}
