//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainCheckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_tbl()
        {
            this.customer_tbl = new HashSet<customer_tbl>();
            this.policy_tbl = new HashSet<policy_tbl>();
            this.quotes = new HashSet<quote>();
        }
    
        public decimal userid { get; set; }
        public string user_F_name { get; set; }
        public string user_M_name { get; set; }
        public string user_L_name { get; set; }
        public decimal user_phone { get; set; }
        public string user_SSN { get; set; }
        public System.DateTime user_DOB { get; set; }
        public string user_email { get; set; }
        public string user_address { get; set; }
        public decimal state_id { get; set; }
        public decimal city_id { get; set; }
        public decimal zip_code { get; set; }
        public bool marital_status { get; set; }
        public bool gender { get; set; }
        public string education_level { get; set; }
        public string employment { get; set; }
        public bool accidents_5years { get; set; }
        public bool traffic_tickets_5years { get; set; }
        public bool DUIs_10years { get; set; }
        public bool suspensions_5years { get; set; }
        public bool defensive_Drive_2years { get; set; }
        public bool military_affiliation { get; set; }
        public bool veteran_status { get; set; }
        public decimal credential_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual credential credential { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_tbl> customer_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_tbl> policy_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quote> quotes { get; set; }
        public virtual state state { get; set; }
    }
}
